### ISSUE TITLE
ASCL

### ISSUE THREAD

**Issue by dbkeitel** [PyFstat/PyFstat#294]
We got an "Astrophysics Source Code Library" entry generated for us: https://ascl.net/2102.027 (Thanks to their editor, Alice Allen.) Two follow-up housekeeping tasks:

We should quote that ID
- [x]  in the README
- [x]  and JOSS paper.

- [x] While we already have a standard license file and citation info in the Readme, they suggest using a separate file for citation info, which seems like a good idea:

> The ASCL recommends that code authors assign a license to their software and make it clear how use of the code should be cited, preferably by use of a CITATION.md, CITATION.cff, or Codemeta.json file added to the root of your code repo. Editable examples of the latter two can be generated by adding /CITATION.cff or /codemeta.json to the link provided above for your code’s entry. Should you choose to use the ASCL entry for citation, a suggested format is available online.

**Comment by dbkeitel** [comment]
#295 adds README badge and codemeta.json file
