### ISSUE TITLE
Discussion on argparse

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [PyFstat/PyFstat#430]
PyFstat implements a basic `argparse` parser dating back to ye ancient ages.

It's not clear to me the exact purpose of such a parser, given that
1) Most functions in this package will be assembled into scripts by a user.
2) Most other functionalities of the parser really should be configured at logger level.

So, the proposal would be:
- [x] Reimplement useful functionalities from argparse into class / method arguments. --> #433 
- [x] Set up logger following the indended way (and solving #163 , maybe). --> #435 
- [x] Remove argparser entirely from this package. --> #435

**Comment by dbkeitel** [comment]
After going through the existing argparse options [as of [ea59401](https://github.com/PyFstat/PyFstat/commit/ea59401e3c076efc23036e3bcacbc0326a87508f)](https://github.com/PyFstat/PyFstat/blob/ea59401e3c076efc23036e3bcacbc0326a87508f/pyfstat/helper_functions.py#L45):
1. `--verbose` and `--quite` (with quite the ancient typo) should be replaced by direct `logging` level manipulation
2. All other options are either deprecated or specific to a few classes, and hence the user should just set the corresponding class options directly, and implement their own `argparse` option for it if they feel like it. But we need to check one-by-one if indeed all of them can be accessed via class options, or are hardcoded to be read from `args` somewhere.

Then the cleanest way would be one PR for 2 first, leaving the logging stuff untouched, and then another for 1 + #163.

**Comment by Rodrigo-Tenorio** [comment]
From the current implementation:
- `verbose` corresponds to `logging.DEBUG`.
- `quite` corresponds to `logging.WARNING`.

**Comment by dbkeitel** [comment]
resolved with #435 I'd say, thanks!
